export declare type Map<T> = {
    [key in string]: T;
};
export declare function get<T extends Map<any>, K1 extends keyof T>(map: T | undefined, key1: K1): T[K1] | undefined;
export declare function get<T extends Map<any>, K1 extends keyof T, K2 extends keyof T[K1]>(map: T | undefined, key1: K1, key2: K2): T[K1][K2] | undefined;
export declare function get<T extends Map<any>, K1 extends keyof T, K2 extends keyof T[K1], K3 extends keyof T[K1][K2]>(map: T | undefined, key1: K1, key2: K2, key3: K3): T[K1][K2][K3] | undefined;
export declare function get<T extends Map<any>, K1 extends keyof T, K2 extends keyof T[K1], K3 extends keyof T[K1][K2], K4 extends keyof T[K1][K2][K3]>(map: T | undefined, key1: K1, key2: K2, key3: K3, key4: K4): T[K1][K2][K3][K4] | undefined;
export declare function get<T extends Map<any>, K1 extends keyof T, K2 extends keyof T[K1], K3 extends keyof T[K1][K2], K4 extends keyof T[K1][K2][K3], K5 extends keyof T[K1][K2][K3][K4]>(map: T | undefined, key1: K1, key2: K2, key3: K3, key4: K4, key5: K5): T[K1][K2][K3][K4][K5] | undefined;
export declare function set<T extends Map<any>, K1 extends keyof T>(map: T | undefined, key1: K1): (value: T[K1]) => T;
export declare function set<T extends Map<any>, K1 extends keyof T, K2 extends keyof T[K1]>(map: T | undefined, key1: K1, key2: K2): (value: T[K1][K2]) => T;
export declare function set<T extends Map<any>, K1 extends keyof T, K2 extends keyof T[K1], K3 extends keyof T[K1][K2]>(map: T | undefined, key1: K1, key2: K2, key3: K3): (value: T[K1][K2][K3]) => T;
export declare function set<T extends Map<any>, K1 extends keyof T, K2 extends keyof T[K1], K3 extends keyof T[K1][K2], K4 extends keyof T[K1][K2][K3]>(map: T | undefined, key1: K1, key2: K2, key3: K3, key4: K4): (value: T[K1][K2][K3][K4]) => T;
export declare function set<T extends Map<any>, K1 extends keyof T, K2 extends keyof T[K1], K3 extends keyof T[K1][K2], K4 extends keyof T[K1][K2][K3], K5 extends keyof T[K1][K2][K3][K4]>(map: T | undefined, key1: K1, key2: K2, key3: K3, key4: K4, key5: K5): (value: T[K1][K2][K3][K4][K5]) => T;
declare type UpdateFn<T> = (value: T) => T;
export declare function update<T extends Map<any>, K1 extends keyof T>(map: T | undefined, key1: K1): (callback: UpdateFn<T[K1]>) => T;
export declare function update<T extends Map<any>, K1 extends keyof T, K2 extends keyof T[K1]>(map: T | undefined, key1: K1, key2: K2): (callback: UpdateFn<T[K1][K2]>) => T;
export declare function update<T extends Map<any>, K1 extends keyof T, K2 extends keyof T[K1], K3 extends keyof T[K1][K2]>(map: T | undefined, key1: K1, key2: K2, key3: K3): (callback: UpdateFn<T[K1][K2][K3]>) => T;
export declare function update<T extends Map<any>, K1 extends keyof T, K2 extends keyof T[K1], K3 extends keyof T[K1][K2], K4 extends keyof T[K1][K2][K3]>(map: T | undefined, key1: K1, key2: K2, key3: K3, key4: K4): (callback: UpdateFn<T[K1][K2][K3][K4]>) => T;
export declare function update<T extends Map<any>, K1 extends keyof T, K2 extends keyof T[K1], K3 extends keyof T[K1][K2], K4 extends keyof T[K1][K2][K3], K5 extends keyof T[K1][K2][K3][K4]>(map: T | undefined, key1: K1, key2: K2, key3: K3, key4: K4, key5: K5): (callback: UpdateFn<T[K1][K2][K3][K4][K5]>) => T;
export declare const toArray: <T>(map: Map<T>) => T[];
export declare function merge<T extends Map<any>, U extends Map<any>>(left: undefined, right: undefined): undefined;
export declare function merge<T extends Map<any>, U extends Map<any>>(left: T, right: undefined): T;
export declare function merge<T extends Map<any>, U extends Map<any>>(left: undefined, right: U): U;
export declare function merge<T extends Map<any>, U extends Map<any>>(left: T, right: U): T & U;
export declare function map<T>(map: Map<T>, callback: (value: T) => T): Map<T>;
export declare function map<T, U>(map: Map<T>, callback: (value: T) => U): Map<U>;
export declare function reduce<T, U>(map: Map<T>, callback: (acc: U, curr: T, index: number) => U, initialValue: U): U;
export {};
